# Generated by Django 5.0.2 on 2024-02-29 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Context', models.TextField()),
                ('organisation', models.TextField(blank=True, null=True)),
                ('announcement_endtime', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, default='file.pdf', null=True, upload_to='uploads/')),
                ('link', models.URLField(blank=True, default='skasc.ac.in', null=True)),
                ('Time', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.course')),
            ],
        ),
    ]
