# Generated by Django 5.0.2 on 2024-02-29 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_anouncement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackstaff',
            old_name='feedback',
            new_name='complaint',
        ),
        migrations.RenameField(
            model_name='feedbackstudent',
            old_name='feedback',
            new_name='complaint',
        ),
    ]
