# Generated by Django 5.0.2 on 2024-03-02 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_fifth_first_four_second_third'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.course'),
        ),
    ]
