# Generated by Django 5.0.2 on 2024-03-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_staff_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anouncement',
            name='announcement_endtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
