# Generated by Django 5.0.2 on 2024-03-03 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_anouncement_announcement_endtime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fifth',
        ),
        migrations.DeleteModel(
            name='first',
        ),
        migrations.DeleteModel(
            name='four',
        ),
        migrations.RemoveField(
            model_name='leavereportstaff',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='leavereportstudent',
            name='student',
        ),
        migrations.DeleteModel(
            name='second',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentresult',
            name='subject',
        ),
        migrations.DeleteModel(
            name='third',
        ),
        migrations.DeleteModel(
            name='LeaveReportStaff',
        ),
        migrations.DeleteModel(
            name='LeaveReportStudent',
        ),
        migrations.DeleteModel(
            name='StudentResult',
        ),
    ]
